document.writeln("<style>");
document.writeln(".foot{ background-color:#d9d9d9;}");
document.writeln(".foot_main{ width:100%; height:110px; background-color:#d9d9d9;}");
document.writeln(".foot_main_center{ width:1000px; height:110px; margin:0 auto; position:relative;}");
document.writeln(".foot_dzjg{ width:50px; height:62px; position:absolute; top:24px; left:0px;}");
document.writeln("/*版权信息*/");
document.writeln(".foot_word{ position:absolute; top:10px; left:80px;}");
document.writeln(".foot_word_r1{ height:32px;}");
document.writeln(".foot_word_r1 span{ padding-left:5px; padding-right:5px;}");
document.writeln(".foot_word_r1 a{ font-size:15px; line-height:32px; cursor:pointer;}");
document.writeln(".foot_word_r2,.foot_word_r3{}");
document.writeln(".foot_word_r2 span,.foot_word_r3 span{ margin-right:10px; font-size:13px; line-height:32px; color:#666;}");
document.writeln(".foot_word_r2 span a{ color:#666;}");
document.writeln(".foot_word_r2 span a:hover{ color:#4178be;}");
document.writeln("/*底部政府链接*/");
document.writeln(".foot_gov_link{ width:220px; height:90px; position:absolute; top:10px; right:0px; border-left:1px solid #b3b3b3;}");
document.writeln("a.gov_link1{ display:block; width:125px; height:30px; position:absolute; top:10px; left:30px; background:url(#) top no-repeat;}");
document.writeln("a.gov_link2{ display:block; width:162px; height:30px; position:absolute; top:50px; left:30px; background:url(#) top no-repeat;}");
document.writeln("/*右侧浮动*/");
document.writeln(".f_right{ width:60px; height:335px; position:fixed; top:50%; right:20px; margin-top:-150px; margin-right:auto; z-index:100;}");
document.writeln(".f_right_main{ width:60px; height:335px; position:relative;}");
document.writeln("a.f_right_sub{ display:block; width:60px; height:60px; position:absolute; left:0px; background-image:url(#); background-repeat:no-repeat; cursor:pointer;}");
document.writeln("a.f_right_sub.sub1{ top:0px; background-position:0px 0px;}");
document.writeln("a.f_right_sub.sub1:hover{ background-position:0px -60px;}");
document.writeln("a.f_right_sub.sub2{ top:61px; background-position:0px -120px;}");
document.writeln("a.f_right_sub.sub2:hover{ background-position:0px -180px;}");
document.writeln("a.f_right_sub.sub3{ top:122px; background-position:0px -240px;}");
document.writeln("a.f_right_sub.sub3:hover{ background-position:0px -300px;}");
document.writeln("a.f_right_sub.sub4{ top:183px; background-position:0px -360px;}");
document.writeln("a.f_right_sub.sub4:hover{ background-position:0px -420px;}");
document.writeln(".f_right_sub.sub4 .f_right_QRcode{ display:none; width:150px; height:140px; position:absolute; left:-150px; bottom:0px; background:url(#) top no-repeat;}");
document.writeln(".f_right_sub.sub4:hover .f_right_QRcode{ display:block;}");
document.writeln("a.f_right_sub.sub5{ top:244px; background-position:0px -480px;}");
document.writeln("a.f_right_sub.sub5:hover{ background-position:0px -540px;}");
document.writeln("");
document.writeln(".f_right_ctrl{ width:60px; height:30px; overflow:hidden; position:absolute; top:305px;}");
document.writeln("a.f_right_sub.sub6{ top:0px; height:30px; background:none; background-color:#999; font-size:15px; line-height:30px; color:#fff; text-align:center;}");
document.writeln("a.f_right_sub.sub6:hover{ background-color:#4496f3;}");
document.writeln("a.f_right_sub.sub7{ display:; top:30px; background-position:0px -630px;}");
document.writeln("@media screen and (max-width:1220px){");
document.writeln("	.f_right{ right:50%; margin-right:-580px;}");
document.writeln("}");
document.writeln("/*便民服务文章页样式-更新1208*/");
document.writeln(".bmfu_art_all .art_date{ height:auto; min-height:32px; overflow:hidden;}");
document.writeln("/*服务一站频道页通样式-更新1209*/");
document.writeln(".fwyzt_r1{ display:none;}");
document.writeln("/*单元格内数字、英文折行行-更新1222*/");
document.writeln("td{ word-break:break-all;}");
document.writeln("/*首页公告公示-更新0106*/");
document.writeln(".sypage1_gggs{ visibility:hidden;}");
document.writeln(".sc_gggs_index .gggs_up{ top:4px;}");
document.writeln(".sc_gggs_index .gggs_down{ bottom:4px;}");
document.writeln("/*首页首屏底部链接-更新0106*/");
document.writeln(".sypage1_link{ margin-top:-30px;}");
document.writeln("/*头尾box-sizing:border-box*/");
document.writeln(".top,");
document.writeln(".top div,");
document.writeln(".top a,");
document.writeln(".top form,");
document.writeln(".top input,");
document.writeln(".top span,");
document.writeln(".foot,");
document.writeln(".foot div,");
document.writeln(".foot a,");
document.writeln(".foot span{ box-sizing:border-box;}");
document.writeln("</style>");
document.writeln("<script type=\"text/javascript\"> ");
document.writeln("function SetHome(obj,vrl){ ");
document.writeln("	try{ ");
document.writeln("		obj.style.behavior=\'url(#default#homepage)\';");
document.writeln("		obj.setHomePage(vrl); ");
document.writeln("		return false;");
document.writeln("	} ");
document.writeln("	catch(e){");
document.writeln("		alert(\'您的浏览器不支持一键设为首页，请到浏览器【设置】功能里操作。\');");
document.writeln("	} ");
document.writeln("}");
document.writeln("</script>");
document.writeln("<div class=\"foot_main\">");
document.writeln("	<div class=\"foot_main_center\">");
document.writeln("    	<div class=\"foot_dzjg\"><a href=\"#\" target=\"_blank\"><img src=\"./resources/login/foot_icon.png\" /></a></div>");
document.writeln("        <div class=\"foot_word\">");
document.writeln("        	<div class=\"foot_word_r1\">");
document.writeln("            	<a href=\"javascript:void(0)\" onclick=\"SetHome(this,window.location)\">设为首页</a>");
document.writeln("                <span>|</span>");
document.writeln("            	<a href=\"#\" target=\"_blank\">关于我们</a>");
document.writeln("                <span>|</span>");
document.writeln("            	<a href=\"#\" target=\"_blank\">本站声明</a>");
document.writeln("                <!--");
document.writeln("                <span>|</span>");
document.writeln("            	<a href=\"#\" target=\"_blank\">新手指南</a>");
document.writeln("                -->");
document.writeln("                <span>|</span>");
document.writeln("            	<a href=\"#\" target=\"_blank\">联系我们</a>");
document.writeln("            </div>");
document.writeln("        	<div class=\"foot_word_r2\">");
document.writeln("            	<span>主办：福建臻善信息科技有限公司 版权所有</span>");
document.writeln("            	<span id=\"cp_chengban\"></span>");
document.writeln("                <span><a href=\"http://www.miitbeian.gov.cn\" target=\"_blank\">备案序号：闽ICP备×××××号</a></span>");
document.writeln("            </div>");
document.writeln("        	<div class=\"foot_word_r3\">");
document.writeln("            	<span>运行管理：龙岩市不动产登记中心</span>");
document.writeln("                <span>地址：福建省龙岩市新罗区西安南路423</span>");
document.writeln("                <span>联系电话：0597-2231934</span>");
document.writeln("            </div>");
document.writeln("        </div>");
//document.writeln("        <div class=\"foot_gov_link\">");
//document.writeln("        	<a class=\"gov_link1\" href=\"http://www.gov.cn/\" target=\"_blank\"></a>");
//document.writeln("        	<a class=\"gov_link2\" href=\"http://www.jiangsu.gov.cn/\" target=\"_blank\"></a>");
//document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<!--右侧浮动-->");
document.writeln("<div class=\"f_right\">");
document.writeln("	<div class=\"f_right_main\">");
document.writeln("    	<a class=\"f_right_sub sub1\" id=\"f_right_member\" href=\"\" target=\"_blank\"></a>");
document.writeln("    	<a class=\"f_right_sub sub2\" href=\"\" target=\"_blank\"></a>");
document.writeln("        <a class=\"f_right_sub sub3\" href=\"\" target=\"_blank\"></a>");
document.writeln("    	<a class=\"f_right_sub sub4\"><div class=\"f_right_QRcode\"></div></a>");
document.writeln("    	<a class=\"f_right_sub sub5\"></a>");
document.writeln("    </div>");
document.writeln("    <div class=\"f_right_ctrl\">");
document.writeln("    	<a class=\"f_right_sub sub6\">收起</a>");
document.writeln("    	<a class=\"f_right_sub sub7\"></a>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<script>");
document.writeln("$(document).ready(function(){");
document.writeln("	//获取webid、webname");
document.writeln("	var f_webid = $(\'.site_local\').attr(\'data\');");
document.writeln("	var f_webname = $(\'.site_local\').text();");
document.writeln("	//设置底部版权承办机构");
document.writeln("	var wx_cbids = [\'6\', \'50\', \'53\', \'51\', \'54\', \'52\', \'49\', \'47\', \'48\', \'115\', \'119\', \'120\'];");
document.writeln("	if(f_webid==\'1\'){");
document.writeln("		$(\'#cp_chengban\').text(\'\');");
document.writeln("	}else if( $.inArray(f_webid,wx_cbids)>-1 ){");
document.writeln("		$(\'#cp_chengban\').text(\'承办：\'+f_webname+\'行政审批局\');");
document.writeln("	}else{");
document.writeln("		$(\'#cp_chengban\').text(\'承办：\'+f_webname+\'政务服务管理办公室\');");
document.writeln("	}");
document.writeln("	//右侧浮动_登录状态");
document.writeln("	$.ajax({");
document.writeln("		url:\'http://www.jszwfw.gov.cn/jszwfw/front/islogin.do\',");
document.writeln("		type:\'post\',");
document.writeln("		dataType : \'json\',");
document.writeln("		async : true,");
document.writeln("		error:function(){},");
document.writeln("		success:function(data){");
document.writeln("			if(data.code == 0){");
document.writeln("				$(\'#f_right_member\').css(\'background-image\',\'url(http://www.jszwfw.gov.cn/picture/2/1612202126339668821.png)\');");
document.writeln("			}else{");
document.writeln("				$(\'#f_right_member\').css(\'background-image\',\'url(http://www.jszwfw.gov.cn/picture/2/1612202126340019953.png)\');");
document.writeln("			}");
document.writeln("		}");
document.writeln("	});");
document.writeln("	//右侧浮动_12345");
document.writeln("	//$(\'a.f_right_sub.sub2\').attr(\'href\',\'/jszwfw/front/smrx/smrxapply.do?webId=\'+f_webid);");
document.writeln("    $(\'a.f_right_sub.sub2\').attr(\'href\',\'http://12345.jszwfw.gov.cn/\');");
document.writeln("	//右侧浮动_纠错链接");
document.writeln("	var f_sub3_a = \'http://www.jszwfw.gov.cn/jact/front/front_mailwrite?sysid=1&groupid=\';");
document.writeln("	var f_local_url = \'&error_url=\' + window.location.href;");
document.writeln("	$(\'a.f_right_sub.sub3\').attr(\'href\',f_sub3_a+f_local_url);");
document.writeln("	//右侧浮动_返回顶部");
document.writeln("	$(\'a.f_right_sub.sub5\').click(function(){");
document.writeln("		$(\'html,body\').stop().animate({scrollTop:0},300);");
document.writeln("	});");
document.writeln("	//右侧浮动_收回展开效果");
document.writeln("	function f_scroll_in(){");
document.writeln("		$(\'a.f_right_sub.sub1,a.f_right_sub.sub2,a.f_right_sub.sub3,a.f_right_sub.sub4,a.f_right_sub.sub5\').stop().animate({top:275},300);");
document.writeln("		//$(\'a.f_right_sub.sub5\').stop().animate({top:214},300);");
document.writeln("		$(\'.f_right_ctrl\').stop().animate({height:\'60px\',top:275},300);");
document.writeln("		$(\'a.f_right_sub.sub6\').stop().animate({top:30},300);");
document.writeln("		$(\'a.f_right_sub.sub7\').stop().animate({top:0},300);");
document.writeln("	}");
document.writeln("	function f_scroll_out(){");
document.writeln("		$(\'a.f_right_sub.sub1\').stop().animate({top:0},300);");
document.writeln("		$(\'a.f_right_sub.sub2\').stop().animate({top:61},300);");
document.writeln("		$(\'a.f_right_sub.sub3\').stop().animate({top:122},300);");
document.writeln("		$(\'a.f_right_sub.sub4\').stop().animate({top:183},300);");
document.writeln("		$(\'a.f_right_sub.sub5\').stop().animate({top:244},300);");
document.writeln("		$(\'.f_right_ctrl\').stop().animate({height:\'30px\',top:305},300);");
document.writeln("		$(\'a.f_right_sub.sub6\').stop().animate({top:0},300);");
document.writeln("		$(\'a.f_right_sub.sub7\').stop().animate({top:30},300);");
document.writeln("	}");
document.writeln("	$(\'a.f_right_sub.sub6\').click(function(){");
document.writeln("		f_scroll_in();");
document.writeln("	});");
document.writeln("	$(\'a.f_right_sub.sub7\').click(function(){");
document.writeln("		f_scroll_out();");
document.writeln("	});");
document.writeln("	//右侧浮动_板块距顶部高度微调");
document.writeln("	function f_scroll_H(){");
document.writeln("		var scroll_H = $(window).scrollTop();");
document.writeln("		if(scroll_H>=250){");
document.writeln("			//f_scroll_out();");
document.writeln("			$(\".f_right\").stop().animate({marginTop:-150},500);");
document.writeln("			setTimeout(f_scroll_out,1000);");
document.writeln("		}else if(scroll_H<250){");
document.writeln("			//f_scroll_in();");
document.writeln("			$(\".f_right\").stop().animate({marginTop:-75},500);");
document.writeln("			setTimeout(f_scroll_in,1000);");
document.writeln("		}");
document.writeln("	}");
document.writeln("	f_scroll_H();");
document.writeln("	$(window).scroll(function(){");
document.writeln("		f_scroll_H();");
document.writeln("	});");
document.writeln("});");
document.writeln("</script>");